# Generated by Django 4.0.4 on 2022-04-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='payment',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='salary',
            field=models.FloatField(null=True),
        ),
    ]
